// supabase/functions/_shared/renderQa.ts
// The RENDER GATE for the demo pages WE generate — the last thing that runs before a bespoke page is
// published to a real prospect. Pure + deterministic; the shared contract is the only import.
//
// Why this exists: previewSpec.ts renders from a spec and therefore cannot break, but the bespoke path
// (src/lib/preview/bespokeSite.ts) hands a language model a blank page and asks for a complete,
// self-contained HTML document. That path has exactly one guard today — bespokeHonest(), which catches
// INVENTED CLAIMS — and none at all for the far more mundane failure: the page is simply BROKEN. A
// truncated document, a Google Fonts <link> the publish target refuses to load, an unreplaced
// {{business_name}}, a hero that ends up blank. We are about to send these at volume to businesses who
// did not ask for them, so a broken page is not a bug, it is a reputation event, and the owner only
// ever sees it once. This module reads the generated bytes and says ship / do not ship.
//
// THE SUBJECT IS OUR OWN OUTPUT, NOT A STRANGER'S SITE. That is the one place this file departs from
// its siblings (a11yScan, trackingScan, mobileScan), and it is worth being explicit about because the
// difference licenses tests that would be reckless anywhere else:
//  - Those scanners describe a business's real website to that business, so every sentence they emit
//    is a claim about someone else and is written to survive being read back in an angry email.
//  - This one describes an artifact we just produced, to ourselves, before anyone sees it. Nothing it
//    says ever reaches a prospect. So an exact tag-balance test — which would false-positive on every
//    hand-maintained legacy page in the world — is fair here, because the input is always a single
//    machine-written document that our own prompt requires to be complete and self-contained.
//
// WHAT THIS DELIBERATELY DOES NOT DO:
//  - It does not judge design, taste, copy quality, or whether the page is BETTER than the prospect's
//    current site. That is a human call and a vision-model call; this is a smoke test for "does it
//    render at all". A page can pass every check here and still be worth killing.
//  - It does not check honesty. bespokeHonest() owns invented credentials, ratings, and tenure. The
//    two gates are independent on purpose — one asks "is it true", this one asks "is it intact" — and
//    a page must clear both.
//  - It does not render anything. There is no browser here, so we never claim a page "looks right",
//    only that specific breakage signatures are present or absent in the bytes.
//  - It does not fetch, resolve, or validate any URL. An external resource is flagged for being
//    cross-origin, never for being dead — we did not look.
//
// THE FALSE-POSITIVE CALCULUS RUNS THE OTHER WAY FROM THE SCANNERS, and every threshold here is set
// from it. A missed break costs one embarrassing email. A wrong BLOCK costs a prospect outright: the
// page is discarded and the fallback template ships instead, so the best demo we had is thrown away
// for no reason. Blocks are therefore reserved for signatures that cannot plausibly occur in a page
// that renders fine, and anything arguable is a 'warn'. Two rules follow from that and are applied
// consistently below:
//
//   1. PRESENCE rules (external_resource, placeholder_text, script_error, unclosed_critical) run
//      against the NARROWEST believable haystack — comments stripped, and script/style bodies stripped
//      wherever the thing we are looking for is markup. A `<img src="https://…">` inside a JS template
//      literal, or inside a commented-out block, is not a resource the browser fetches, and must never
//      block a page.
//   2. ABSENCE rules (no_contact_path, no_title, no_viewport, no_h1) run against the WIDEST believable
//      haystack, because claiming a thing is missing is the easier mistake to make and the more
//      expensive one. If a tel: link exists anywhere in the document we accept it and move on.
//
// HONESTY: every issue traces to a signature really present (or really absent) in the string passed
// in. Nothing is estimated, scored, or predicted; there is no "quality" number here because we have no
// way to measure one. Where the page could plausibly render fine despite the signature, the issue is a
// 'warn' and says what was observed, not what will happen.
//
// EMPTY / NON-DOCUMENT INPUT: render.not_html is TERMINAL — when the input is not a recognizable HTML
// document we emit that single issue and stop. Every other rule presupposes a document, and reporting
// "no <h1>" or "thin content" about an empty string or a fenced code block is noise that buries the
// one fact the operator needs. So renderQa('') claims exactly one thing, the only thing observable:
// this is not an HTML document. It deliberately does NOT return ok:true — a gate that waves an empty
// string through would defeat the entire purpose of the file.
//
// Runs in Deno (the publish path) and under tsx (renderQa.verify.ts) — the .ts extension on the import
// is required by Deno and harmless under tsx.

import {
  accessibleName,
  attr,
  elements,
  innerText,
  openTags,
  snippet,
  stripNonContent,
} from './scanTypes.ts';

/** One thing observed about the generated page. `block` ⇒ do not publish. */
export interface RenderIssue {
  /** Stable machine code, e.g. 'render.external_resource'. NEVER renumber — publish logs join on this. */
  code: string;
  severity: 'block' | 'warn';
  /** One observational sentence: what was seen, counted, or not found. Operator-facing, never prospect-facing. */
  message: string;
}

/** The gate's verdict. `ok` is exactly "no block issues" — warns never stop a publish. */
export interface RenderQa {
  ok: boolean;
  issues: RenderIssue[];
}

/**
 * Every code this gate can emit, in the order it emits them (blocks first, then warns).
 * Exported so the publish path can enumerate/whitelist without string-hunting through this file.
 * AT MOST ONE ISSUE PER CODE is ever returned — findings of the same kind are aggregated with a count
 * and a capped example list, so `issues.length` is bounded by this array and a page with 40 broken
 * images produces one line, not forty.
 */
export const RENDER_QA_CODES = [
  'render.not_html',
  'render.empty_body',
  'render.external_resource',
  'render.unclosed_critical',
  'render.placeholder_text',
  'render.no_contact_path',
  'render.script_error',
  'render.no_viewport',
  'render.no_title',
  'render.thin_content',
  'render.no_h1',
  'render.img_missing_alt',
] as const;

/**
 * Visible-character floors. These are low on purpose. The question a floor answers is not "is this
 * page good" but "did generation collapse" — a real bespoke landing page runs to several thousand
 * visible characters, so 200 only catches a document whose body is genuinely empty, and 600 only
 * catches one that got cut off early. Setting them anywhere near a plausible page length would start
 * blocking short-but-fine pages, which is the expensive mistake.
 */
export const EMPTY_BODY_CHARS = 200;
export const THIN_CONTENT_CHARS = 600;

/** How many example values a message will list before summarising the rest. Keeps a log line readable. */
const EXAMPLE_CAP = 5;

/** Tags whose opening/closing counts must agree. A mismatch is the signature of a truncated generation. */
const CRITICAL_TAGS = ['html', 'head', 'body', 'div', 'section'] as const;

// ─── Attribute reading ───────────────────────────────────────────────────────────────────────────
// The shared attr()/hasAttr() helpers anchor on \b, so asking them for `src` on
// `<script data-src="https://cdn.example/x.js">` matches inside `data-src` and hands back the URL of
// something the browser never fetches. For a BLOCK rule that is not a cosmetic difference — it is a
// wrongly-discarded demo. a11yScan.ts hit the identical problem with `id`/`tabindex` and solved it the
// same way: isolate a bare `name="value"` pair first (one not glued to a preceding word character or
// hyphen), then hand that slice to the shared helper so the quoting rules stay in exactly one place.

/** attr(), but refusing `data-`/vendor look-alikes. Delegates the actual quote handling to attr(). */
function bareAttr(attrs: string, name: string): string | null {
  const m = new RegExp(`(?:^|[\\s"'/])(${name}\\s*=\\s*(?:"[^"]*"|'[^']*'|[^\\s"'>]+))`, 'i').exec(attrs);
  return m ? attr(m[1], name) : null;
}

/**
 * True when the attribute is really present on THIS element, valueless forms included.
 * hasAttr() is the wrong tool for `alt`: it matches `data-alt` too, which suppresses a real
 * missing-alt warning on our own generated markup. Under-reporting is the safe direction when the
 * subject is a stranger's site (a11yScan leans that way deliberately); here the subject is a page we
 * wrote and are about to send as proof that we fix exactly this failure, so we want to actually see it.
 */
function bareHasAttr(attrs: string, name: string): boolean {
  return new RegExp(`(?:^|[\\s"'/])${name}(?:\\s*=|[\\s/>]|$)`, 'i').test(attrs);
}

// ─── Text extraction ─────────────────────────────────────────────────────────────────────────────

/**
 * Visible text of the document body: tags removed, entities collapsed, whitespace normalised.
 * Expects markup that has already been through stripNonContent(), so script/style bodies and comments
 * are gone and none of them can pad the count. Entities become a single space each, which can only
 * ever UNDER-count (`&mdash;` is one visible character, `&nbsp;&nbsp;` collapses to one space) — with
 * a floor as low as 200 that slack is irrelevant, and it is the direction that never inflates a page
 * into looking fuller than it is.
 *
 * When the body never closes (a truncated document) we take everything after `<body>` rather than
 * giving up: the unclosed tags are reported by their own rule, and refusing to count the text here
 * would stack a phantom empty_body on top of it.
 */
function visibleText(clean: string): string {
  const open = /<body\b[^>]*>/i.exec(clean);
  const region = open
    ? clean.slice(open.index + open[0].length).replace(/<\/body\s*>[\s\S]*$/i, ' ')
    : clean;
  return region
    .replace(/<[^>]*>/g, ' ')
    .replace(/&[a-zA-Z]+;|&#\d+;|&#x[0-9a-fA-F]+;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/** Join a capped example list onto a message without ever printing forty URLs into a log line. */
function examples(values: string[]): string {
  const shown = values.slice(0, EXAMPLE_CAP).map((v) => snippet(v)).join(', ');
  const rest = values.length - EXAMPLE_CAP;
  return rest > 0 ? `${shown}, and ${rest} more` : shown;
}

// ─── External resources ──────────────────────────────────────────────────────────────────────────

/**
 * True for a URL the publish target will refuse. Cross-origin requests are blocked there, so an
 * absolute http(s) reference does not degrade — it renders broken, which is worse than not being
 * there at all.
 *
 * Allowed, and deliberately so: `data:` URIs (the whole point of a self-contained document), relative
 * and root-relative paths, `#` fragments, and any non-fetching scheme (`mailto:`, `tel:`). Protocol-
 * relative `//host/path` IS flagged — it is absolute and cross-origin, it just hides it.
 *
 * The prospect's own image URLs are flagged like anyone else's. They are the tempting exception and
 * the one that bites: hotlinking a photo off the site we are pitching to replace means the demo breaks
 * the moment they change anything, and it is fetched cross-origin regardless, so it is already broken
 * on arrival. Nothing about "it belongs to them" makes the request succeed.
 */
function isBlockedUrl(url: string | null): boolean {
  const s = (url ?? '').trim();
  if (!s) return false;
  return /^(?:https?:)?\/\//i.test(s);
}

/**
 * Every absolute http(s) resource the page really asks the browser to fetch, in document order,
 * de-duplicated. Each source is read from the narrowest haystack that can still contain it:
 *  - `noComments`  markup with comments removed — a commented-out <script src> is not a request.
 *  - `noScripts`   the above, minus <script> bodies — a `<img src="https://…">` written inside a JS
 *                  template literal is a string, not an image, and must not block the page.
 * <a href> is never inspected: a link to an external site is normal, correct, and does not render.
 */
function blockedResources(noComments: string, noScripts: string): string[] {
  const found: string[] = [];
  const add = (u: string | null) => { if (isBlockedUrl(u)) found.push((u ?? '').trim()); };

  // <script src> — read from noComments because stripping script bodies would take the tag with it.
  for (const t of openTags(noComments, 'script')) add(bareAttr(t.attrs, 'src'));

  // <link rel="stylesheet" href> — only stylesheets. A rel="canonical" or rel="preconnect" is metadata
  // or a hint; neither renders broken, so neither is a reason to discard a page.
  for (const t of openTags(noScripts, 'link')) {
    if (/\bstylesheet\b/i.test(bareAttr(t.attrs, 'rel') ?? '')) add(bareAttr(t.attrs, 'href'));
  }

  // <img src> and <img srcset> — same tag, same breakage, so srcset is covered under the same code
  // rather than left as a hole a responsive hero image could walk through.
  for (const t of openTags(noScripts, 'img')) {
    add(bareAttr(t.attrs, 'src'));
    for (const cand of (bareAttr(t.attrs, 'srcset') ?? '').split(',')) add(cand.trim().split(/\s+/)[0] ?? null);
  }

  // url() in CSS — the single most common way an AI-written page reaches off-host, because
  // `@import url('https://fonts.googleapis.com/…')` is muscle memory. Read from real CSS only:
  // <style> element bodies, plus inline style="" attributes taken from markup with <script> removed,
  // so `const css = "background:url(https://…)"` inside a script cannot block the page.
  const cssRegions: string[] = elements(noComments, 'style').map((e) => e.inner);
  const styleAttr = /(?:^|[\s"'/])style\s*=\s*(?:"([^"]*)"|'([^']*)')/gi;
  let sm: RegExpExecArray | null;
  while ((sm = styleAttr.exec(noScripts))) cssRegions.push(sm[1] ?? sm[2] ?? '');
  const urlFn = /url\(\s*(?:"([^"]*)"|'([^']*)'|([^)'"\s]*))\s*\)/gi;
  for (const css of cssRegions) {
    urlFn.lastIndex = 0; // reused across regions — reset so the walk is order-independent
    let um: RegExpExecArray | null;
    while ((um = urlFn.exec(css))) add(um[1] ?? um[2] ?? um[3] ?? null);
  }

  return [...new Set(found)];
}

// ─── Placeholder text ────────────────────────────────────────────────────────────────────────────

/**
 * Unreplaced scaffolding in the VISIBLE copy. Every pattern here is one a reader would see and
 * immediately understand as "this was sent to me by a robot that did not finish".
 *
 * Case sensitivity is load-bearing, not fussiness. `TODO` is uppercase-only because "todo" is an
 * ordinary Spanish word ("todo el día", "todo incluido") and we generate pages for Spanish-speaking
 * businesses; a case-insensitive match would block every one of them. `XXX` is uppercase and
 * \b-anchored so a clothing shop's "XXXL" survives while a "555-XXX-XXXX" phone stub does not.
 *
 * The bracketed-token pattern requires four or more characters so a legitimate "[NEW]" badge is not
 * mistaken for "[YOUR NAME]".
 *
 * These run over visible text extracted from stripNonContent() output, which is what makes the whole
 * set safe: `${count}` in a JS template literal, a `{{mustache}}` in a commented-out block, and
 * "lorem ipsum" inside a CSS content property are all invisible to the reader and invisible here.
 */
const PLACEHOLDER_PATTERNS: [string, RegExp][] = [
  ['lorem ipsum', /\blorem\s+ipsum\b/i],
  ['TODO marker', /\bTODO\b/],
  ['FIXME marker', /\bFIXME\b/],
  ['XXX marker', /\bXXX\b/],
  ['unreplaced {{token}}', /\{\{[^}]*\}\}/],
  ['unreplaced ${token}', /\$\{[^}]*\}/],
  ['[BRACKETED PLACEHOLDER]', /\[[A-Z][A-Z0-9_ ]{3,}\]/],
  ['"your … here" stub', /\byour\s+(?:text|content|copy|headline|tagline|message|name|logo|image|photo|business)\s+here\b/i],
];

// ─── Inline script sanity ────────────────────────────────────────────────────────────────────────

/** What a walk over one inline script found. Nothing here is a judgement — only shape. */
interface JsShape {
  /** `{` minus `}` outside strings/comments/regexes. >0 unclosed, <0 extra. */
  delta: number;
  /** Input ended while still inside a template literal (or inside a `${}` of one). */
  openTemplate: boolean;
  /** A `/*` comment never closed, so everything after it went unread and `delta` means nothing. */
  openComment: boolean;
}

/** After these, a `/` opens a regex literal rather than dividing. */
const REGEX_AFTER = new Set([
  'return', 'typeof', 'instanceof', 'in', 'of', 'new', 'delete', 'void',
  'case', 'do', 'else', 'yield', 'await', 'throw',
]);

/** Whether a `/` at this point starts a regex literal or is a division operator. */
function regexCanStart(prev: string, prevWord: string): boolean {
  if (!prev) return true;                                   // start of source
  if (/[)\]}]/.test(prev)) return false;                    // end of an expression → division
  if (/[A-Za-z0-9_$]/.test(prev)) return REGEX_AFTER.has(prevWord); // identifier → division, keyword → regex
  if (prev === '"' || prev === "'" || prev === '`') return false;   // string end → division
  return true;                                              // operator or punctuation → regex
}

/**
 * Walk one script's source and report its brace balance and whether it ended mid-literal.
 *
 * Written as an explicit walk rather than the regex strip-and-count in qa.ts because that approach
 * cannot tell an unterminated template literal from a terminated one — and "unterminated template
 * literal" is precisely the truncation signature we are here to catch. It also lets `${…}` be walked
 * as real code, so braces inside an interpolation are counted once and correctly.
 *
 * `allowRegex` exists for the conservatism pass described in scriptIssues(): the regex-vs-division
 * call is the one genuinely ambiguous decision in JS lexing, and running the walk both ways lets us
 * refuse to block whenever the answer depends on getting it right.
 *
 * A plain string that runs to a newline is treated as closed there rather than swallowing the rest of
 * the file. Real JS cannot span a line in a quoted string anyway, and recovering keeps one stray
 * apostrophe from turning the whole brace count into fiction.
 */
function lexJs(src: string, allowRegex: boolean): JsShape {
  // Bottom frame is the script body itself; a frame is pushed per template literal and per `${`.
  const stack: { mode: 'code' | 'tmpl'; brace: number }[] = [{ mode: 'code', brace: 0 }];
  let prev = '';       // last significant character in code context
  let prevWord = '';   // last identifier/keyword, for the `return /re/` case
  let i = 0;

  while (i < src.length) {
    const top = stack[stack.length - 1];

    if (top.mode === 'tmpl') {
      const c = src[i];
      if (c === '\\') { i += 2; continue; }
      if (c === '`') { stack.pop(); prev = '`'; i++; continue; }
      if (c === '$' && src[i + 1] === '{') { stack.push({ mode: 'code', brace: 0 }); prev = '{'; prevWord = ''; i += 2; continue; }
      i++;
      continue;
    }

    const c = src[i];
    if (/\s/.test(c)) { i++; continue; }                    // whitespace never changes context

    if (c === '/' && src[i + 1] === '/') {                  // line comment
      const nl = src.indexOf('\n', i);
      if (nl < 0) break;
      i = nl + 1;
      continue;
    }
    if (c === '/' && src[i + 1] === '*') {                  // block comment
      const end = src.indexOf('*/', i + 2);
      if (end < 0) return { delta: stack[0].brace, openTemplate: false, openComment: true };
      i = end + 2;
      continue;
    }
    if (c === '/' && allowRegex && regexCanStart(prev, prevWord)) {  // regex literal
      i++;
      let inClass = false;
      while (i < src.length) {
        const d = src[i];
        if (d === '\\') { i += 2; continue; }
        if (d === '\n') break;                              // regexes cannot span lines — bail, recover
        if (d === '[') inClass = true;
        else if (d === ']') inClass = false;
        else if (d === '/' && !inClass) { i++; break; }
        i++;
      }
      while (i < src.length && /[a-z]/i.test(src[i])) i++;  // flags
      prev = '/'; prevWord = '';
      continue;
    }
    if (c === '"' || c === "'") {                           // quoted string
      const q = c;
      i++;
      while (i < src.length) {
        const d = src[i];
        if (d === '\\') { i += 2; continue; }
        if (d === q) { i++; break; }
        if (d === '\n') break;                              // recover rather than swallow the file
        i++;
      }
      prev = q; prevWord = '';
      continue;
    }
    if (c === '`') { stack.push({ mode: 'tmpl', brace: 0 }); i++; continue; }
    if (c === '{') { top.brace++; prev = '{'; prevWord = ''; i++; continue; }
    if (c === '}') {
      // Closing the `${` that pushed this frame returns us to the surrounding template literal.
      if (top.brace === 0 && stack.length > 1) { stack.pop(); prev = '`'; i++; continue; }
      top.brace--; prev = '}'; prevWord = ''; i++;
      continue;
    }
    if (/[A-Za-z0-9_$]/.test(c)) {                          // identifier/keyword run
      let j = i;
      while (j < src.length && /[A-Za-z0-9_$]/.test(src[j])) j++;
      prevWord = src.slice(i, j);
      prev = src[j - 1];
      i = j;
      continue;
    }
    prev = c; prevWord = '';
    i++;
  }

  return { delta: stack[0].brace, openTemplate: stack.length > 1, openComment: false };
}

/** `type` values we will lex as JavaScript. Anything else (`application/ld+json`, `text/template`,
 *  `importmap`) is data the browser never executes, and counting its braces would be meaningless. */
const JS_TYPES = new Set(['', 'text/javascript', 'application/javascript', 'module']);

/**
 * Descriptions of inline scripts that are syntactically broken. Aggressively conservative, because
 * this is the block most likely to misfire and the one whose subject matter is hardest to parse with
 * regexes.
 *
 * Two guards do the work:
 *  - An unterminated `/*` comment abandons the brace count entirely. Everything after the comment was
 *    never read, so any delta computed from it is fiction.
 *  - A brace imbalance is reported only when a second walk that treats every `/` as division agrees,
 *    with the same sign. The regex-vs-division call is the one real ambiguity in lexing JS; if the
 *    verdict depends on resolving it, we decline to block. That means a genuine imbalance hidden
 *    behind a regex literal goes unreported — the correct direction, since a missed break costs one
 *    email and a wrong block costs the prospect.
 *
 * External scripts are skipped: their content is not here, and their URL is already the business of
 * render.external_resource.
 */
function scriptIssues(noComments: string): string[] {
  const broken: string[] = [];
  for (const el of elements(noComments, 'script')) {
    if (bareAttr(el.attrs, 'src')) continue;
    if (!JS_TYPES.has((bareAttr(el.attrs, 'type') ?? '').trim().toLowerCase())) continue;
    const src = el.inner;
    if (!src.trim()) continue;

    const shape = lexJs(src, true);
    if (shape.openTemplate) { broken.push('unterminated template literal'); continue; }
    if (shape.openComment) continue;                        // brace count unreadable — say nothing
    if (shape.delta === 0) continue;

    const naive = lexJs(src, false);
    if (naive.openTemplate || naive.openComment) continue;   // the two walks disagree about shape
    if (naive.delta === 0 || Math.sign(naive.delta) !== Math.sign(shape.delta)) continue;

    broken.push(shape.delta > 0
      ? `${shape.delta} unclosed '{'`
      : `${Math.abs(shape.delta)} unmatched '}'`);
  }
  return broken;
}

// ─── The gate ────────────────────────────────────────────────────────────────────────────────────

/**
 * Screen one generated HTML document for breakage. Pure, deterministic, and total: any string is a
 * valid input and produces a verdict.
 *
 * Read the result as "no breakage signature was detected", never as "the page is good". This gate
 * cannot see layout, contrast, overflow, whether a font fell back, or whether the copy is any good —
 * a page that clears it still deserves the human glance it gets before send.
 */
export function renderQa(html: string): RenderQa {
  const raw = html || '';
  const issues: RenderIssue[] = [];
  const block = (code: string, message: string) => issues.push({ code, severity: 'block', message });
  const warn = (code: string, message: string) => issues.push({ code, severity: 'warn', message });
  const done = (): RenderQa => ({ ok: issues.every((i) => i.severity !== 'block'), issues });

  // Three views of the document, each the narrowest one its rules can honestly use. See the
  // presence/absence split in the file header.
  const noComments = raw.replace(/<!--[\s\S]*?-->/g, ' ');            // comments never render
  const noScripts = noComments.replace(/<script[\s\S]*?<\/script>/gi, ' '); // markup outside JS
  const clean = stripNonContent(raw);                                  // renderable markup only

  // ── render.not_html — terminal ─────────────────────────────────────────────────────────────────
  // A leading BOM, whitespace, or a generator comment before the doctype is fine; browsers cope and
  // so do we. A markdown code fence, a prose preamble, or an empty string is not fine, and neither is
  // a document with no <body> — our generator is required to emit one, so its absence means the
  // output is a fragment rather than a page.
  const lead = raw.replace(/^﻿/, '').replace(/^(?:\s|<!--[\s\S]*?-->)+/, '');
  const startsAsDoc = /^<!doctype\s+html/i.test(lead) || /^<html\b/i.test(lead);
  const hasBody = /<body\b/i.test(noComments);
  if (!startsAsDoc || !hasBody) {
    const why = [
      startsAsDoc ? null : 'it does not begin with a doctype or an <html> tag',
      hasBody ? null : 'it contains no <body> element',
    ].filter(Boolean).join(' and ');
    block('render.not_html', `The output is not a complete HTML document: ${why}.`);
    return done(); // every rule below presupposes a document; reporting them here would only add noise
  }

  const text = visibleText(clean);

  // ── render.empty_body ──────────────────────────────────────────────────────────────────────────
  if (text.length < EMPTY_BODY_CHARS) {
    block('render.empty_body', `The body holds ${text.length} visible character${text.length === 1 ? '' : 's'} (floor is ${EMPTY_BODY_CHARS}) — the page renders effectively blank.`);
  }

  // ── render.external_resource ───────────────────────────────────────────────────────────────────
  const external = blockedResources(noComments, noScripts);
  if (external.length > 0) {
    block('render.external_resource', `${external.length} absolute http(s) resource${external.length === 1 ? ' is' : 's are'} referenced in a <script src>, <link rel=stylesheet>, <img src>, or CSS url(). The publish target blocks cross-origin requests, so ${external.length === 1 ? 'it renders' : 'they render'} broken: ${examples(external)}.`);
  }

  // ── render.unclosed_critical ───────────────────────────────────────────────────────────────────
  // Counted on `clean`, so a `<div>` written inside a script string, a style block, or a comment
  // cannot skew the tally. Exact balance is the test — see the header on why that is fair for a
  // machine-written single-file document and would not be for a hand-maintained site.
  const unbalanced: string[] = [];
  for (const tag of CRITICAL_TAGS) {
    const open = openTags(clean, tag).length;
    const close = (clean.match(new RegExp(`</${tag}\\s*>`, 'gi')) ?? []).length;
    if (open !== close) unbalanced.push(`${tag} (${open} opening, ${close} closing)`);
  }
  if (unbalanced.length > 0) {
    block('render.unclosed_critical', `Opening and closing tag counts do not match for ${unbalanced.join(', ')} — the document is malformed or was cut off mid-generation.`);
  }

  // ── render.placeholder_text ────────────────────────────────────────────────────────────────────
  // Matched against visible text only. A prospect reading "{{business_name}}" in their own hero is the
  // most embarrassing single outcome this file exists to prevent.
  const stubs: string[] = [];
  const stubHits: string[] = [];
  for (const [label, re] of PLACEHOLDER_PATTERNS) {
    const m = re.exec(text);
    if (m) { stubs.push(label); stubHits.push(m[0]); }
  }
  if (stubs.length > 0) {
    block('render.placeholder_text', `Unreplaced placeholder text is visible on the page — ${stubs.join(', ')}: ${examples(stubHits)}.`);
  }

  // ── render.no_contact_path ─────────────────────────────────────────────────────────────────────
  // Widest possible haystack, and the accepted set is widened past the spec to include sms:, because
  // the failure mode of this rule is discarding a page that had a perfectly good way to get in touch.
  // A demo with no route to contact is worse than the site it replaces, so its absence is a block —
  // but only when nothing anywhere in the document looks like one.
  const hasContact = /\b(?:tel|mailto|sms):/i.test(raw) || /<form\b/i.test(raw);
  if (!hasContact) {
    block('render.no_contact_path', 'No tel:, mailto: or sms: reference and no <form> appears anywhere in the document — the page offers a visitor no way to make contact.');
  }

  // ── render.script_error ────────────────────────────────────────────────────────────────────────
  const broken = scriptIssues(noComments);
  if (broken.length > 0) {
    block('render.script_error', `${broken.length} inline <script> ${broken.length === 1 ? 'is' : 'are'} syntactically broken (${examples(broken)}) — the browser will abort ${broken.length === 1 ? 'it' : 'them'}, so any motion or reveal it drives never runs.`);
  }

  // ── Warnings ───────────────────────────────────────────────────────────────────────────────────
  // These never stop a publish, so they can afford to be tighter than the blocks above: a warn that
  // misfires costs an operator four seconds of reading, not a prospect.

  // No viewport meta: the page renders at desktop width on a phone. Any non-empty content= is accepted
  // rather than second-guessing the value.
  const viewport = openTags(noScripts, 'meta').some((t) =>
    (bareAttr(t.attrs, 'name') ?? '').trim().toLowerCase() === 'viewport' && (bareAttr(t.attrs, 'content') ?? '').trim().length > 0);
  if (!viewport) {
    warn('render.no_viewport', 'No <meta name="viewport"> with a content value was found — the page will render at desktop width on a phone.');
  }

  // Title: read from <head> when there is one, so an inline <svg><title> in the body cannot stand in
  // for the document title.
  const headHtml = /<head\b[^>]*>[\s\S]*?<\/head>/i.exec(noScripts)?.[0] ?? noScripts;
  const title = (innerText(headHtml, 'title') ?? '').trim();
  if (!title) {
    warn('render.no_title', 'The document has no <title>, or its <title> is empty — the browser tab and any shared link will show the raw URL.');
  }

  // Thin content. Suppressed when empty_body already fired: one page, one verdict about its length.
  if (text.length >= EMPTY_BODY_CHARS && text.length < THIN_CONTENT_CHARS) {
    warn('render.thin_content', `The body holds ${text.length} visible characters (under ${THIN_CONTENT_CHARS}) — thin for a landing page, and a sign a section may have been dropped.`);
  }

  // An <h1> with an actual accessible name. accessibleName() handles the wordmark case where the
  // heading contains only an <img alt="…">, which is a real and correct pattern, not a bug.
  const hasH1 = elements(clean, 'h1').some((e) => accessibleName(e.attrs, e.inner).length > 0);
  if (!hasH1) {
    warn('render.no_h1', 'No <h1> carrying visible text was found — the page has no top-level heading for search engines or screen readers.');
  }

  // Images with no alt attribute at all. alt="" is the correct markup for a decorative image and is
  // deliberately not counted. We sell against exactly this failure, so shipping it in our own demo is
  // worth surfacing even though it does not break rendering.
  const altless = openTags(clean, 'img').filter((t) => {
    const role = (bareAttr(t.attrs, 'role') ?? '').toLowerCase();
    if (role === 'presentation' || role === 'none') return false;
    if ((bareAttr(t.attrs, 'aria-hidden') ?? '').toLowerCase() === 'true') return false;
    return !bareHasAttr(t.attrs, 'alt');
  });
  if (altless.length > 0) {
    warn('render.img_missing_alt', `${altless.length} <img> element${altless.length === 1 ? ' has' : 's have'} no alt attribute — the exact failure this demo is meant to fix: ${examples(altless.map((t) => t.raw))}.`);
  }

  return done();
}

/**
 * One log-safe line explaining a verdict, for the publish path's rejection record.
 * Blocks only — warns are for the operator's eyes, not for the reason a page was withheld.
 */
export function renderQaReason(result: RenderQa): string {
  const blocks = result.issues.filter((i) => i.severity === 'block');
  return blocks.length === 0
    ? 'no blocking render issues detected'
    : blocks.map((i) => `${i.code}: ${i.message}`).join(' | ');
}
