// src/lib/garvis/bigCities.ts
// The BROAD discovery grid — every major US metro, for the "scrape everything" pool (verified by
// bigCities.verify.ts). Flat [city, state] (no region needed here): the on-demand discover-run engine
// crosses these with the whole LOCAL_NICHES catalog so the operator sweeps ALL local businesses
// nationwide, not a niche. Merged from the top US markets; deduped. Real cities only.

export type Metro = readonly [city: string, state: string];

export const BIG_METROS: readonly Metro[] = [
  ['New York', 'NY'],
  ['Los Angeles', 'CA'],
  ['Chicago', 'IL'],
  ['Houston', 'TX'],
  ['Phoenix', 'AZ'],
  ['Philadelphia', 'PA'],
  ['San Antonio', 'TX'],
  ['San Diego', 'CA'],
  ['Dallas', 'TX'],
  ['Jacksonville', 'FL'],
  ['Austin', 'TX'],
  ['Fort Worth', 'TX'],
  ['San Jose', 'CA'],
  ['Columbus', 'OH'],
  ['Charlotte', 'NC'],
  ['Indianapolis', 'IN'],
  ['San Francisco', 'CA'],
  ['Seattle', 'WA'],
  ['Denver', 'CO'],
  ['Oklahoma City', 'OK'],
  ['Nashville', 'TN'],
  ['Washington', 'DC'],
  ['El Paso', 'TX'],
  ['Las Vegas', 'NV'],
  ['Boston', 'MA'],
  ['Detroit', 'MI'],
  ['Portland', 'OR'],
  ['Louisville', 'KY'],
  ['Memphis', 'TN'],
  ['Baltimore', 'MD'],
  ['Milwaukee', 'WI'],
  ['Albuquerque', 'NM'],
  ['Tucson', 'AZ'],
  ['Fresno', 'CA'],
  ['Sacramento', 'CA'],
  ['Kansas City', 'MO'],
  ['Mesa', 'AZ'],
  ['Atlanta', 'GA'],
  ['Omaha', 'NE'],
  ['Colorado Springs', 'CO'],
  ['Raleigh', 'NC'],
  ['Virginia Beach', 'VA'],
  ['Long Beach', 'CA'],
  ['Miami', 'FL'],
  ['Oakland', 'CA'],
  ['Minneapolis', 'MN'],
  ['Tulsa', 'OK'],
  ['Bakersfield', 'CA'],
  ['Wichita', 'KS'],
  ['Arlington', 'TX'],
  ['Aurora', 'CO'],
  ['Tampa', 'FL'],
  ['New Orleans', 'LA'],
  ['Cleveland', 'OH'],
  ['Honolulu', 'HI'],
  ['Anaheim', 'CA'],
  ['Lexington', 'KY'],
  ['Stockton', 'CA'],
  ['Corpus Christi', 'TX'],
  ['Henderson', 'NV'],
  ['Riverside', 'CA'],
  ['Newark', 'NJ'],
  ['Saint Paul', 'MN'],
  ['Santa Ana', 'CA'],
  ['Cincinnati', 'OH'],
  ['Irvine', 'CA'],
  ['Orlando', 'FL'],
  ['Pittsburgh', 'PA'],
  ['St. Louis', 'MO'],
  ['Greensboro', 'NC'],
  ['Jersey City', 'NJ'],
  ['Anchorage', 'AK'],
  ['Lincoln', 'NE'],
  ['Plano', 'TX'],
  ['Durham', 'NC'],
  ['Buffalo', 'NY'],
  ['Chandler', 'AZ'],
  ['Chula Vista', 'CA'],
  ['Toledo', 'OH'],
  ['Madison', 'WI'],
  ['Gilbert', 'AZ'],
  ['Reno', 'NV'],
  ['Fort Wayne', 'IN'],
  ['St. Petersburg', 'FL'],
  ['Lubbock', 'TX'],
  ['Irving', 'TX'],
  ['Winston-Salem', 'NC'],
  ['Chesapeake', 'VA'],
  ['Glendale', 'AZ'],
  ['Scottsdale', 'AZ'],
  ['Norfolk', 'VA'],
  ['Boise', 'ID'],
  ['Richmond', 'VA'],
  ['Spokane', 'WA'],
  ['Baton Rouge', 'LA'],
  ['Tacoma', 'WA'],
  ['Des Moines', 'IA'],
  ['Birmingham', 'AL'],
  ['Salt Lake City', 'UT'],
  ['Providence', 'RI'],
  ['Hartford', 'CT'],
  ['Charleston', 'SC'],
  ['Columbia', 'SC'],
  ['Little Rock', 'AR'],
  ['Jackson', 'MS'],
  ['Manchester', 'NH'],
  ['Portland', 'ME'],
  ['Burlington', 'VT'],
  ['Wilmington', 'DE'],
  ['Charleston', 'WV'],
  ['Fargo', 'ND'],
  ['Sioux Falls', 'SD'],
  ['Billings', 'MT'],
  ['Cheyenne', 'WY'],
  ['Laredo', 'TX'],
  ['Hialeah', 'FL'],
  ['Garland', 'TX'],
  ['North Las Vegas', 'NV'],
  ['Fremont', 'CA'],
  ['San Bernardino', 'CA'],
  ['Modesto', 'CA'],
  ['Fontana', 'CA'],
  ['Rochester', 'NY'],
  ['Oxnard', 'CA'],
  ['Moreno Valley', 'CA'],
  ['Fayetteville', 'NC'],
  ['Aurora', 'IL'],
  ['Glendale', 'CA'],
  ['Yonkers', 'NY'],
  ['Huntington Beach', 'CA'],
  ['Montgomery', 'AL'],
  ['Amarillo', 'TX'],
  ['Akron', 'OH'],
  ['Columbus', 'GA'],
  ['Augusta', 'GA'],
  ['Grand Rapids', 'MI'],
  ['Shreveport', 'LA'],
  ['Huntsville', 'AL'],
  ['Mobile', 'AL'],
  ['Tallahassee', 'FL'],
  ['Grand Prairie', 'TX'],
  ['Overland Park', 'KS'],
  ['Knoxville', 'TN'],
  ['Worcester', 'MA'],
  ['Brownsville', 'TX'],
  ['Newport News', 'VA'],
  ['Santa Clarita', 'CA'],
  ['Port St. Lucie', 'FL'],
  ['Fort Lauderdale', 'FL'],
  ['Chattanooga', 'TN'],
  ['Tempe', 'AZ'],
  ['Oceanside', 'CA'],
  ['Garden Grove', 'CA'],
  ['Rancho Cucamonga', 'CA'],
  ['Cape Coral', 'FL'],
  ['Santa Rosa', 'CA'],
  ['Vancouver', 'WA'],
  ['Peoria', 'AZ'],
  ['Ontario', 'CA'],
  ['Elk Grove', 'CA'],
  ['Springfield', 'MO'],
  ['Pembroke Pines', 'FL'],
  ['Salem', 'OR'],
  ['Corona', 'CA'],
  ['Eugene', 'OR'],
  ['McKinney', 'TX'],
  ['Fort Collins', 'CO'],
  ['Lancaster', 'CA'],
  ['Palmdale', 'CA'],
  ['Pomona', 'CA'],
  ['Torrance', 'CA'],
  ['Orange', 'CA'],
  ['Fullerton', 'CA'],
  ['Pasadena', 'CA'],
  ['El Monte', 'CA'],
  ['Downey', 'CA'],
  ['Costa Mesa', 'CA'],
  ['Carlsbad', 'CA'],
  ['Inglewood', 'CA'],
  ['Ventura', 'CA'],
  ['West Covina', 'CA'],
  ['Norwalk', 'CA'],
  ['Burbank', 'CA'],
  ['Murrieta', 'CA'],
  ['Temecula', 'CA'],
  ['El Cajon', 'CA'],
  ['Vista', 'CA'],
  ['San Marcos', 'CA'],
  ['Escondido', 'CA'],
  ['Thousand Oaks', 'CA'],
  ['Simi Valley', 'CA'],
  ['Mission Viejo', 'CA'],
];

/** As {city, state} objects for buildDiscoveryQueries. */
export function bigMetroCities(): Array<{ city: string; state: string }> {
  return BIG_METROS.map(([city, state]) => ({ city, state }));
}
