// supabase/functions/generate-app/index.ts
// The server-side generation pipeline (provider keys never reach the browser). PORTED to the modern
// contract — identical to the client's directGenerate: seeds the fixed Vite + TS scaffold + UI kit,
// generates a blueprint (with design + structured integrations), a Supabase migration, a per-app
// palette, the app source via the §FILE protocol, generates edge functions for integrations + a secret
// manifest, then self-heals against the static QA checks. All prompts/scaffold/QA come from the shared
// canonical modules — no more divergent Sandpack prompt. Progress streams to project_generations.

import { createClient, type SupabaseClient } from 'npm:@supabase/supabase-js@2';
import { complete, completeStream, parseJson, corsHeaders, modelForPlan, type AIMessage } from '../_shared/ai.ts';
import {
  GENERATE_SYSTEM, GENERATE_FILES_STREAM, EDIT_SYSTEM_STREAM,
  blueprintPrompt, filesPromptStream, SCHEMA_SYSTEM, schemaPrompt,
} from '../_shared/prompts.ts';
import { SCAFFOLD_FILES, SCAFFOLD_PATHS } from '../_shared/scaffold.ts';
import { checkCredits, spendCredits, InsufficientCreditsError, getUserPlan } from '../_shared/credits.ts';
import { buildIndexCssForHue } from '../_shared/themePresets.ts';
import { validateProject, issuesToFixRequest } from '../_shared/qa.ts';
import { parseProtocol } from '../_shared/streamparse.ts';

const STAGES = [
  'interpret', 'blueprint', 'schema', 'file_tree', 'frontend',
  'backend', 'auth_logic', 'styling', 'validate', 'fix', 'summarize',
] as const;
type Stage = (typeof STAGES)[number];

// A typed Supabase client for generated apps (matches the client's GENERATED_SUPABASE_CLIENT).
const GENERATED_SUPABASE_CLIENT = `// src/lib/supabaseClient.ts — generated by FableForge.
import { createClient } from '@supabase/supabase-js';

const url = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const anonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

if (!url || !anonKey) {
  console.warn('[supabase] VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY are not set — running on localStorage until you connect a backend.');
}

export const supabase = createClient(url || 'https://placeholder.supabase.co', anonKey || 'placeholder-anon-key');
export const isSupabaseConnected = Boolean(url && anonKey);
`;
const GENERATED_ENV_EXAMPLE = `# Supabase — create a project at https://supabase.com, open Project Settings > API,
# then paste the values here and rename this file to .env
VITE_SUPABASE_URL=
VITE_SUPABASE_ANON_KEY=
`;

function stripFences(s: string): string {
  const m = s.match(/```(?:sql)?\s*([\s\S]*?)```/i);
  return (m ? m[1] : s).trim();
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  const supabaseAdmin = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  );
  const authClient = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_ANON_KEY')!,
    { global: { headers: { Authorization: req.headers.get('Authorization') ?? '' } } },
  );

  const { data: { user } } = await authClient.auth.getUser();
  if (!user) return json({ error: 'Unauthorized' }, 401);

  const { projectId, prompt, planContext } = await req.json();
  if (!projectId || !prompt) return json({ error: 'projectId and prompt are required' }, 400);

  const { data: project } = await supabaseAdmin
    .from('projects').select('id, owner_id, name').eq('id', projectId).single();
  if (!project || project.owner_id !== user.id) return json({ error: 'Project not found' }, 404);

  // CREDIT GATE — a full app build is the most expensive action; reject up front if the balance
  // can't cover it (replaces the old generation-count limit with the unified credit balance).
  try {
    await checkCredits(supabaseAdmin, user.id, 'generation');
  } catch (e) {
    if (e instanceof InsufficientCreditsError) return json({ error: e.message }, 402);
    throw e;
  }

  const { data: gen, error: genErr } = await supabaseAdmin
    .from('project_generations')
    .insert({ project_id: projectId, user_id: user.id, prompt, kind: 'create', status: 'running' })
    .select().single();
  if (genErr) return json({ error: genErr.message }, 500);

  runPipeline(supabaseAdmin, gen.id, projectId, user.id, prompt, planContext).catch(async (err) => {
    await supabaseAdmin.from('project_generations').update({
      status: 'failed', error: String(err), finished_at: new Date().toISOString(),
    }).eq('id', gen.id);
    await supabaseAdmin.from('projects').update({ status: 'error' }).eq('id', projectId);
    await supabaseAdmin.from('error_logs').insert({
      user_id: user.id, project_id: projectId, generation_id: gen.id,
      source: 'pipeline', message: String(err),
    }).then(() => {}, () => {});
  });

  return json({ generationId: gen.id });
});

async function runPipeline(db: SupabaseClient, genId: string, projectId: string, userId: string, prompt: string, planContext?: string) {
  let totalIn = 0, totalOut = 0, totalCost = 0;
  const m = modelForPlan(await getUserPlan(db, userId)); // free → cheap model; paid → operator model
  const stageLog: { stage: Stage; status: string; started_at: string; finished_at?: string; note?: string }[] = [];

  const mark = async (stage: Stage, status: 'running' | 'done', note?: string) => {
    if (status === 'running') stageLog.push({ stage, status, started_at: new Date().toISOString(), note });
    else {
      const entry = stageLog.find((s) => s.stage === stage);
      if (entry) { entry.status = 'done'; entry.finished_at = new Date().toISOString(); entry.note = note; }
    }
    await db.from('project_generations').update({
      current_stage: stage, stages: stageLog, input_tokens: totalIn, output_tokens: totalOut, cost_usd: totalCost,
    }).eq('id', genId);
  };
  const ask = async (messages: AIMessage[], maxTokens = 8192) => {
    const r = await complete(messages, { maxTokens, provider: m.provider, model: m.model });
    totalIn += r.inputTokens; totalOut += r.outputTokens; totalCost += r.costUsd;
    return r.text;
  };
  // STREAMING variant — required for the long file-generation step: a non-streaming call at high
  // max_tokens risks the provider's stream-required threshold + socket timeouts (mirrors the client,
  // which streams this step). Also avoids withRetry replaying the most expensive call on a transient error.
  const askStream = async (messages: AIMessage[], maxTokens: number) => {
    const r = await completeStream(messages, { maxTokens, provider: m.provider, model: m.model }, () => {});
    totalIn += r.inputTokens; totalOut += r.outputTokens; totalCost += r.costUsd;
    return r.text;
  };
  // JSON with one repair round-trip (mirrors the client's parseJsonWithRepair) so a minor formatting
  // glitch doesn't hard-fail the whole generation.
  const askJson = async <T,>(messages: AIMessage[], maxTokens = 8192): Promise<T> => {
    const text = await ask(messages, maxTokens);
    try { return parseJson<T>(text); }
    catch {
      const fixed = await ask([{ role: 'system', content: 'Return ONLY the corrected JSON object — no prose, no fences.' }, { role: 'user', content: text }], maxTokens);
      return parseJson<T>(fixed);
    }
  };
  const writeFile = async (path: string, content: string) => {
    await db.from('project_files').upsert(
      { project_id: projectId, path, content, updated_by_ai: true }, { onConflict: 'project_id,path' },
    );
  };
  const fetchAll = async (): Promise<{ path: string; content: string }[]> => {
    const { data } = await db.from('project_files').select('path, content').eq('project_id', projectId).is('deleted_at', null);
    return (data ?? []) as { path: string; content: string }[];
  };
  const reserved = new Set([...SCAFFOLD_PATHS, '/src/lib/supabaseClient.ts', '/supabase/migrations/0001_init.sql', '/.env.example']);
  const keepable = (p: string) => !reserved.has(p) && !p.startsWith('/src/components/ui/');

  // ---- interpret + blueprint ----
  await mark('interpret', 'running'); await mark('interpret', 'done', 'Prompt parsed');
  await mark('blueprint', 'running');
  const bpUser = planContext ? `${prompt}\n\nThe user reviewed and approved this plan — follow it:\n${planContext}` : prompt;
  const blueprint = await askJson<Record<string, unknown>>([
    { role: 'system', content: GENERATE_SYSTEM }, { role: 'user', content: blueprintPrompt(bpUser) },
  ]);
  try {
    await db.from('app_blueprints').insert({
      project_id: projectId, app_name: blueprint.app_name ?? 'Untitled app', description: blueprint.description ?? null,
    });
  } catch { /* app_blueprints is non-essential to the generation */ }
  await db.from('projects').update({
    name: (blueprint.app_name as string) ?? 'Untitled app', description: (blueprint.description as string) ?? null, status: 'generating',
  }).eq('id', projectId);
  await mark('blueprint', 'done', (blueprint.app_name as string) ?? undefined);

  // ---- integration manifest (drives edge-function generation + the secret popup) ----
  const integrations = Array.isArray(blueprint.integrations) ? (blueprint.integrations as Record<string, unknown>[]) : [];
  const requiredSecrets: { env: string; service: string; purpose: string; status: 'missing' }[] = [];
  for (const it of integrations) {
    const service = typeof it.service === 'string' ? it.service : '';
    const purpose = typeof it.purpose === 'string' ? it.purpose : '';
    const secrets = Array.isArray(it.secrets) ? it.secrets : [];
    for (const s of secrets) if (typeof s === 'string' && s.trim()) requiredSecrets.push({ env: s.trim(), service, purpose, status: 'missing' });
  }
  const secretEnvs = [...new Set(requiredSecrets.map((s) => s.env))];
  const manifestSecrets = secretEnvs.map((env) => requiredSecrets.find((s) => s.env === env));
  const secretServices = [...new Set(requiredSecrets.map((s) => s.service).filter(Boolean))];
  const hasIntegrations = integrations.length > 0;

  // ---- backend (Supabase migration) ----
  await mark('schema', 'running');
  let hasBackend = false, backendFiles = 0, backendNote = 'no backend needed';
  const tables = (blueprint.database_schema as { tables?: unknown[] } | undefined)?.tables;
  if (Array.isArray(tables) && tables.length) {
    try {
      const sql = stripFences(await ask([{ role: 'system', content: SCHEMA_SYSTEM }, { role: 'user', content: schemaPrompt(JSON.stringify(blueprint)) }]));
      if (sql && !/^--\s*no tables required/i.test(sql)) {
        await writeFile('/supabase/migrations/0001_init.sql', sql + '\n');
        await writeFile('/src/lib/supabaseClient.ts', GENERATED_SUPABASE_CLIENT);
        await writeFile('/.env.example', GENERATED_ENV_EXAMPLE);
        hasBackend = true; backendFiles = 3; backendNote = `${tables.length} tables + RLS + auth`;
      }
    } catch (e) { backendNote = 'skipped (' + (e instanceof Error ? e.message : 'error') + ')'; }
  }
  if (hasIntegrations && !hasBackend) {
    await writeFile('/src/lib/supabaseClient.ts', GENERATED_SUPABASE_CLIENT);
    await writeFile('/.env.example', GENERATED_ENV_EXAMPLE);
  }
  await mark('schema', 'done', backendNote);

  // ---- seed the fixed scaffold + per-app palette ----
  await mark('file_tree', 'running');
  for (const f of SCAFFOLD_FILES) await writeFile(f.path, f.content);
  const design = blueprint.design as { accentHue?: unknown; headingFont?: unknown } | undefined;
  const accentHue = Number(design?.accentHue);
  if (Number.isFinite(accentHue)) {
    const headingFont = typeof design?.headingFont === 'string' ? design.headingFont : undefined;
    await writeFile('/src/index.css', buildIndexCssForHue(accentHue, headingFont));
  }

  // ---- app source (§FILE protocol) + edge functions for integrations ----
  const filesText = await askStream([
    { role: 'system', content: GENERATE_FILES_STREAM },
    { role: 'user', content: filesPromptStream(JSON.stringify(blueprint), hasBackend, hasIntegrations) },
  ], 32000);
  const appFiles = parseProtocol(filesText).changes.filter((f) => f.path && f.content.trim() && keepable(f.path));
  if (!appFiles.length) throw new Error('The model produced no source files.');
  for (const f of appFiles) await writeFile(f.path, f.content);
  if (hasIntegrations) {
    await writeFile('/supabase/.fableforge/secrets.json', JSON.stringify({ secrets: manifestSecrets, integrations }, null, 2) + '\n');
  }
  const total = SCAFFOLD_FILES.length + appFiles.length + backendFiles;
  await mark('file_tree', 'done', `${total} files`);
  for (const s of ['frontend', 'backend', 'auth_logic', 'styling'] as Stage[]) await mark(s, 'done');

  // ---- verify + self-heal against the static QA checks (no more no-op validate/fix) ----
  await mark('validate', 'running');
  let qaErrors = validateProject(await fetchAll()).filter((i) => i.severity === 'error');
  await mark('validate', 'done', qaErrors.length ? `${qaErrors.length} issue(s) found` : 'clean');
  if (qaErrors.length) {
    await mark('fix', 'running');
    for (let attempt = 0; attempt < 2 && qaErrors.length; attempt++) {
      try {
        const current = (await fetchAll()).filter((f) => keepable(f.path) || f.path.startsWith('/src/'));
        const fixMsg = issuesToFixRequest(qaErrors) + '\n\nRespond with §ACTION edit only — fix the root cause of each issue and change nothing else. Do not plan or ask.';
        const parsed = parseProtocol(await askStream([
          { role: 'system', content: EDIT_SYSTEM_STREAM },
          { role: 'user', content: `Current files:\n${JSON.stringify(current)}\n\nLatest request from the user: ${fixMsg}` },
        ], 16000));
        if (parsed.action === 'edit') {
          for (const c of parsed.changes) if (c.path && keepable(c.path)) await writeFile(c.path, c.content);
          for (const p of parsed.deletions) await db.from('project_files').update({ deleted_at: new Date().toISOString() }).eq('project_id', projectId).eq('path', p);
        }
      } catch { break; }
      qaErrors = validateProject(await fetchAll()).filter((i) => i.severity === 'error');
    }
    await mark('fix', 'done', qaErrors.length ? `${qaErrors.length} unresolved` : 'fixed');
  } else {
    await mark('fix', 'done');
  }
  const unresolved = qaErrors.length;

  // ---- summarize + persist ----
  await mark('summarize', 'running');
  const summary = `Generated ${total} files for ${blueprint.app_name}.` +
    (hasBackend ? ` It's full-stack: a Supabase backend (${backendNote}) at /supabase/migrations/0001_init.sql, talked to through /src/lib/db.ts.` : '') +
    (secretEnvs.length ? ` Wires up ${secretServices.join(', ') || 'external services'} via edge functions — add ${secretEnvs.join(', ')} in Secrets to go live.` : '') +
    (unresolved ? ` Note: ${unresolved} static issue(s) remain — open the preview and use Fix with AI.` : ' Open the preview to try it.');
  await mark('summarize', 'done');

  await db.from('ai_messages').insert({
    project_id: projectId, user_id: userId, generation_id: genId,
    role: 'assistant', content: summary, files_changed: appFiles.map((f) => f.path),
  });
  await spendCredits(db, userId, {
    costUsd: totalCost, kind: 'generation', provider: m.provider, model: m.model,
    inputTokens: totalIn, outputTokens: totalOut, projectId,
  });
  await db.from('projects').update({ status: 'ready', updated_at: new Date().toISOString() }).eq('id', projectId);
  await db.from('project_generations').update({
    status: 'succeeded', summary, finished_at: new Date().toISOString(),
    input_tokens: totalIn, output_tokens: totalOut, cost_usd: totalCost,
  }).eq('id', genId);
  await db.from('audit_logs').insert({
    actor_id: userId, action: 'project.generate', entity_type: 'project', entity_id: projectId,
    metadata: { generation_id: genId, files: total },
  }).then(() => {}, () => {});
}

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, 'content-type': 'application/json' } });
}
